<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="Scheduler" nsURI="gssi.astra.scheduler" nsPrefix="gssi.astra.scheduler">
  <eClassifiers xsi:type="ecore:EClass" name="SchedulerModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="tableTask" upperBound="-1"
        eType="#//TableTask" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TableTask" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="tasks" upperBound="-1"
        eType="#//Task" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Task" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="priority" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="following" upperBound="-1"
        eType="#//Task"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="duration" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="acts" lowerBound="1" upperBound="-1"
        eType="#//ACT" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ACT" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="start" lowerBound="1" eType="#//Tick"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="end" lowerBound="1" eType="#//Tick"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="period" lowerBound="1"
        eType="#//Period"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tick" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="TBD"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Period">
    <eLiterals name="TICK_INTO_TSLICE"/>
    <eLiterals name="TICK_INTO_SLICE_8_4" value="1"/>
  </eClassifiers>
</ecore:EPackage>
